export const Chpt1SubDetail=[
{title:"বিশ্বগ্রাম",
    name:"Global_village"
},
{title:"ভার্চুয়াল রিয়েলিটি",
    name:"virtual_reality"},
{title:"আর্টিফিসিয়াল ইন্টেলিজেন্স",
    name:"AI"},
{title:"রোবটিক্স",
    name:"Robotics"},
{title:"ক্রায়োসার্জারি",
    name:"Cryosurgery"},
{title:"জেনেটিক ইঞ্জিনিয়ারিং",
    name:"Genetic_Engineering"},
{title:"ন্যানোটেকনোলজি",
    name:"Nano_Technology"},
{title:"বায়োইনফরমেটিক্স",
    name:"Bio_Informatics"},
    {title:"ভার্চুয়াল রিয়েলিটি",
        name:"virtual_reality"},
]